[package]
name = "rust_serialization_benchmark"
version = "0.1.0"
authors = ["theduke <chris@theduke.at>"]

[dependencies]
bencher = { git = "https://github.com/theduke/bencher.git" }
serde = "0.8"
serde_derive = "0.8"

serde_json = "0.8"
bincode = { version = "0.6", features = ["serde"] }

